CREATE SEQUENCE role_id_seq;

CREATE TABLE IF NOT EXISTS TB_ROLE (
  ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('role_id_seq'),
  NAME VARCHAR(255) NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
  UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
);

INSERT INTO TB_ROLE(ID, NAME) VALUES (1, 'ADMINISTRADOR');

SELECT setval('role_id_seq', 1);