INSERT INTO TB_USER (ID, NAME, EMAIL, LOGIN, PASSWORD, ACTIVE)
VALUES (1, 'Administrador', 'gabriel-silva_2011@hotmail.com', '@dmin_2', '$2a$10$RYtz23zhOKtGZT2Qylo2UeGFi4yVq/Q4qLzIiQLYvfSD2gDnYzLBG', true);

INSERT INTO TB_USER (ID, NAME, EMAIL, LOGIN, PASSWORD, ACTIVE)
VALUES (2, 'Rafael', 'rafaelnascimentojv@gmail.com', 'r@fael_33', '$2a$10$RYtz23zhOKtGZT2Qylo2UeGFi4yVq/Q4qLzIiQLYvfSD2gDnYzLBG', true);

INSERT INTO TB_USER (ID, NAME, EMAIL, LOGIN, PASSWORD, ACTIVE)
VALUES (3, 'Claudionilton', 'claudioniltonjose@gmail.com', 'cl@udio_154', '$2a$10$RYtz23zhOKtGZT2Qylo2UeGFi4yVq/Q4qLzIiQLYvfSD2gDnYzLBG', true);

SELECT setval('tb_user_id_seq', 3);

-- ADMINISTRADOR --
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 1);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 2);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 3);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 4);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 5);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 6);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 7);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 8);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 9);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 10);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 11);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 12);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 13);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 14);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 15);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 16);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 17);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 18);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 19);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (1, 20);

-- RAFAEL --
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 1);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 2);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 3);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 4);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 5);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 6);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 7);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 8);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 9);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 10);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 11);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 12);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 13);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 14);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 15);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 16);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 17);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 18);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 19);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (2, 20);

-- CLAUDIONILTON --
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 1);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 2);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 3);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 4);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 5);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 6);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 7);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 8);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 9);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 10);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 11);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 12);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 13);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 14);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 15);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 16);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 17);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 18);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 19);
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) values (3, 20);