CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; -- criando uuid

CREATE SEQUENCE IF NOT EXISTS tb_role_id_seq;

CREATE TABLE IF NOT EXISTS TB_ROLE (
  ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('tb_role_id_seq'),
  NAME VARCHAR(255) NOT NULL UNIQUE,
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
  UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
);
