CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; -- criando uuid

CREATE SEQUENCE IF NOT EXISTS tb_user_id_seq;

CREATE TABLE IF NOT EXISTS TB_USER (
  ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('tb_user_id_seq'),
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  LOGIN VARCHAR(20) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ACTIVE BOOLEAN NOT NULL,
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
  UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp  
);