CREATE SEQUENCE IF NOT EXISTS tb_measurement_id_seq;

CREATE TABLE IF NOT EXISTS TB_MEASUREMENT_UNIT(
    ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('tb_measurement_id_seq'),
    NAME VARCHAR(50) NOT NULL,
    PREFIX VARCHAR(15) NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
);