CREATE SEQUENCE IF NOT EXISTS tb_product_id_seq;

CREATE TABLE IF NOT EXISTS TB_PRODUCT(
    ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('tb_product_id_seq'),
    BRAND_ID INTEGER NOT NULL REFERENCES TB_BRAND(ID),
    MEASUREMENT_UNIT_ID INTEGER NOT NULL REFERENCES TB_MEASUREMENT_UNIT(ID),
    NAME VARCHAR(255) NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
    SERIAL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
);