CREATE SEQUENCE IF NOT EXISTS tb_stock_id_seq;

CREATE TABLE IF NOT EXISTS TB_STOCK(
    ID INTEGER PRIMARY KEY NOT NULL DEFAULT NEXTVAL('tb_stock_id_seq'),
    PRODUCT_ID INTEGER NOT NULL REFERENCES TB_PRODUCT(ID),
    QTD INTEGER NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE DEFAULT TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
);