CREATE OR REPLACE FUNCTION FUNC_PRODUCT_INPUT_AI()
 RETURNS trigger AS $$

 DECLARE COUNT_STOCK INTEGER;

BEGIN

    SELECT COUNT(*) INTO COUNT_STOCK FROM TB_STOCK WHERE ID_PRODUCT = NEW.ID_PRODUCT;

    IF COUNT_STOCK > 0 THEN
        UPDATE TB_STOCK SET
            QTD = QTD + NEW.QTD,
            UPDATED_AT = TO_CHAR(now(), 'yyyy-MM-dd HH24:mm:ss')::timestamp
        WHERE ID_PRODUCT = NEW.ID_PRODUCT;

    ELSE

        INSERT INTO TB_STOCK(ID_PRODUCT, QTD) VALUES (NEW.ID_PRODUCT, NEW.QTD);

    END IF;

    RETURN NULL;
END;
$$
LANGUAGE 'plpgsql';

DROP TRIGGER IF EXISTS TRG_PRODUCT_INPUT_AI ON PUBLIC.TB_PRODUCT_INPUT;

CREATE TRIGGER TRG_PRODUCT_INPUT_AI
AFTER INSERT ON TB_PRODUCT_INPUT
FOR EACH ROW EXECUTE PROCEDURE FUNC_PRODUCT_INPUT_AI();